try to fix keep-deployment-alive job

diff --git a/.github/workflows/keep-deployment-awake.yml b/.github/workflows/keep-deployment-awake.yml
--- a/.github/workflows/keep-deployment-awake.yml
+++ b/.github/workflows/keep-deployment-awake.yml
@@ -12,3 +12,6 @@ jobs:
       - name: Ping frontend URL
         run: |
           curl -fsSL https://stock-price-prediction-frontend.onrender.com/ || echo "Ping failed"
+      - name: Ping backend health check
+        run: |
+          curl -fsSL https://stock-price-prediction-backend-541r.onrender.com/health || echo "Ping failed"
